project:
  type: book

book:
  title: "Applied Economics Research Course"
  author: "Bas Machielsen"
  date: "04/04/2026"
  chapters:
    - part: "Lecture Info and Slides"
      chapters:
        - index.qmd
        - text: "Lecture 1"
          href: slides/lecture1_introduction/introduction.pdf
        - text: "Lecture 2"
          href: slides/lecture2_data_wrangling/data_wrangling.pdf
        - text: "Lecture 3"
          href: slides/lecture3_geographic_rdd_and_fe/presentation3.pdf
        - text: "Example Presentation (PDF)"
          href: slides/example_presentation/example_presentation.pdf
    - part: "Notebooks"
      chapters:
        - notebooks/compute_roads_distance_wijk.qmd
        - notebooks/bbox_to_polygon_geocode.qmd
        - notebooks/compute_gridfile_around_re_border.qmd
        - notebooks/rdd_re_netherlands.qmd
       # - notebooks/france_roads_persistence.qmd
        - notebooks/roman_roads_pop_density.qmd
       # - notebooks/synthetic_control_example.qmd
        - notebooks/france_roads_persistence.qmd

bibliography: references.bib

resources:
  - slides/example_presentation/example_presentation.pdf

format:
  html:
    theme: cosmo

render:
  - "*.qmd"
  - "!slides/*"
